/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eBrain;


import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.graphstream.algorithm.Prim;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author luigy
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jd_mapaMental = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_add_palabra = new javax.swing.JTextField();
        jb_agregarPalabras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_add_palabra1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cb_add_palabra2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        sp_add_prioridad = new javax.swing.JSpinner();
        jb_crearRelacion = new javax.swing.JButton();
        jb_agregarMapaMental = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tf_nombreGrafo = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_add_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rb_add_masculino = new javax.swing.JRadioButton();
        rb_add_femenino = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cb_add_raza = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dc_add_Fnacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_add_obs = new javax.swing.JTextArea();
        bt_add = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cb_mod_perfil = new javax.swing.JComboBox<>();
        tf_mod_nombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rb_mod_masculino = new javax.swing.JRadioButton();
        rb_mod_femenino = new javax.swing.JRadioButton();
        cb_mod_raza = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dc_mod_Fnacimiento = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mod_obs = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cb_mod_perfilMapa = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cb_mod_palabraMapa = new javax.swing.JComboBox<>();
        tf_mod_palabraMapa = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lb_mod_palabraMapa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cb_mod_conexionMapa = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        sp_mod_prioridadMapa = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cb_mod_mapa = new javax.swing.JComboBox<>();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jc_perfiles = new javax.swing.JComboBox<>();
        jl_perfil = new javax.swing.JLabel();
        jl_mapaMental = new javax.swing.JLabel();
        jc_mapasMentales = new javax.swing.JComboBox<>();
        jb_mostrarMapa = new javax.swing.JButton();
        jb_mostrarPrim = new javax.swing.JButton();
        jb_actualizarTodo = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Mapa mental");

        jLabel7.setText("Palabra");

        jb_agregarPalabras.setText("AGREGAR");
        jb_agregarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarPalabrasActionPerformed(evt);
            }
        });

        jLabel8.setText("____________________________________________________________");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Palabras");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Relaciones");

        cb_add_palabra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_add_palabra1ActionPerformed(evt);
            }
        });

        jLabel11.setText("---------->");

        jLabel12.setText("Prioridad");

        sp_add_prioridad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        sp_add_prioridad.setValue(1);

        jb_crearRelacion.setText("CREAR RELACION");
        jb_crearRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearRelacionActionPerformed(evt);
            }
        });

        jb_agregarMapaMental.setText("AGREGAR MAPA MENTAL");
        jb_agregarMapaMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarMapaMentalActionPerformed(evt);
            }
        });

        jButton3.setText("FINALIZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel22.setText("Nombre:");

        javax.swing.GroupLayout jd_mapaMentalLayout = new javax.swing.GroupLayout(jd_mapaMental.getContentPane());
        jd_mapaMental.getContentPane().setLayout(jd_mapaMentalLayout);
        jd_mapaMentalLayout.setHorizontalGroup(
            jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel6))
                    .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mapaMentalLayout.createSequentialGroup()
                                        .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_add_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_nombreGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jb_agregarPalabras))))))
                    .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                                    .addComponent(cb_add_palabra1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_add_palabra2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sp_add_prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jb_crearRelacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_agregarMapaMental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_mapaMentalLayout.setVerticalGroup(
            jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapaMentalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_nombreGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_add_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agregarPalabras))
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_add_palabra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cb_add_palabra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_mapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(sp_add_prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_crearRelacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_agregarMapaMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Genero");

        buttonGroup1.add(rb_add_masculino);
        rb_add_masculino.setSelected(true);
        rb_add_masculino.setText("Masculino");

        buttonGroup1.add(rb_add_femenino);
        rb_add_femenino.setText("Femenino");

        jLabel3.setText("Raza");

        cb_add_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asiatico", "Africano", "Arabe" }));

        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setText("Observacion");

        ta_add_obs.setColumns(20);
        ta_add_obs.setRows(5);
        jScrollPane1.setViewportView(ta_add_obs);

        bt_add.setText("CREAR");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_add_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_add_masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_add_femenino))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dc_add_Fnacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_add_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_add_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rb_add_masculino)
                    .addComponent(rb_add_femenino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_add_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dc_add_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_add)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Perfil", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("sdfdf", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        jLabel13.setText("Perfil");

        cb_mod_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mod_perfilActionPerformed(evt);
            }
        });

        jLabel14.setText("Nombre");

        jLabel15.setText("Genero");

        buttonGroup2.add(rb_mod_masculino);
        rb_mod_masculino.setSelected(true);
        rb_mod_masculino.setText("Masculino");

        buttonGroup2.add(rb_mod_femenino);
        rb_mod_femenino.setText("Femenino");

        cb_mod_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Raza");

        jLabel17.setText("Fecha de naciiento");

        ta_mod_obs.setColumns(20);
        ta_mod_obs.setRows(5);
        jScrollPane2.setViewportView(ta_mod_obs);

        jLabel18.setText("Observacion");

        jButton2.setText("GUARDAR CAMBIOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("ELIMINAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_mod_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_mod_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_mod_masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_mod_femenino))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_mod_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dc_mod_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_mod_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_mod_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rb_mod_masculino)
                    .addComponent(rb_mod_femenino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_mod_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(dc_mod_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Perfil", jPanel4);

        jPanel6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel6ComponentShown(evt);
            }
        });

        cb_mod_perfilMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mod_perfilMapaActionPerformed(evt);
            }
        });

        jLabel19.setText("Perfil");

        jLabel20.setText("Palabra");

        cb_mod_palabraMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mod_palabraMapaActionPerformed(evt);
            }
        });

        jButton5.setText("GUARDAR CAMBIOS");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Conexion");

        jLabel23.setText("----------->");

        cb_mod_conexionMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mod_conexionMapaActionPerformed(evt);
            }
        });

        jLabel24.setText("Prioridad");

        sp_mod_prioridadMapa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jButton6.setText("GUARDAR CAMBIOS");

        jLabel26.setText("Mapa mental");

        cb_mod_mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mod_mapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_mod_palabraMapa, 0, 168, Short.MAX_VALUE)
                            .addComponent(tf_mod_palabraMapa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lb_mod_palabraMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(cb_mod_conexionMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addGap(8, 8, 8)
                        .addComponent(sp_mod_prioridadMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_mod_mapa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_mod_perfilMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mod_perfilMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cb_mod_mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_mod_palabraMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_mod_palabraMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mod_palabraMapa)
                    .addComponent(jLabel23)
                    .addComponent(cb_mod_conexionMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(sp_mod_prioridadMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Mapa Mental", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        jc_perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_perfilesActionPerformed(evt);
            }
        });

        jl_perfil.setText("Perfil");

        jl_mapaMental.setText("Mapa Mental");

        jb_mostrarMapa.setText("Mostrar Mapa Mental");
        jb_mostrarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mostrarMapaActionPerformed(evt);
            }
        });

        jb_mostrarPrim.setText("Mostrar Prim");
        jb_mostrarPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mostrarPrimActionPerformed(evt);
            }
        });

        jb_actualizarTodo.setText("Actualizar");
        jb_actualizarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_mostrarPrim, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jl_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jc_perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jl_mapaMental))
                            .addComponent(jb_mostrarMapa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_actualizarTodo)
                            .addComponent(jc_mapasMentales, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jb_actualizarTodo, jb_mostrarMapa});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_perfil)
                    .addComponent(jc_perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_mapaMental)
                    .addComponent(jc_mapasMentales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_mostrarMapa)
                    .addComponent(jb_actualizarTodo))
                .addGap(18, 18, 18)
                .addComponent(jb_mostrarPrim)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Perfil", jPanel9);

        jTabbedPane1.addTab("Ejercicio", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel6ComponentShown
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < perfiles.size(); i++) {
            modelo.addElement(perfiles.get(i));
        }
        this.cb_mod_perfilMapa.setModel(modelo);

    }//GEN-LAST:event_jPanel6ComponentShown

    private void cb_mod_mapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mod_mapaActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < ((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getNodeCount(); i++) {
            modelo.addElement(((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getNode(i));
        }
        this.cb_mod_palabraMapa.setModel(modelo);
    }//GEN-LAST:event_cb_mod_mapaActionPerformed

    private void cb_mod_conexionMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mod_conexionMapaActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < ((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdgeCount(); i++) {
            if (((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdge(i).getNode0().toString().equals(this.cb_mod_palabraMapa.getSelectedItem().toString())
                &&((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdge(i).getNode1().toString().equals(this.cb_mod_conexionMapa.getSelectedItem().toString())) {
                // this.sp_mod_prioridadMapa.setValue(((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdge(i).);
            }
        }
    }//GEN-LAST:event_cb_mod_conexionMapaActionPerformed

    private void cb_mod_palabraMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mod_palabraMapaActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        this.tf_mod_palabraMapa.setText(this.cb_mod_palabraMapa.getSelectedItem().toString());
        this.lb_mod_palabraMapa.setText(this.cb_mod_palabraMapa.getSelectedItem().toString());
        for (int i = 0; i < ((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdgeCount(); i++) {
            if (((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdge(i).getNode0().toString().equals(this.cb_mod_palabraMapa.getSelectedItem().toString())) {
                modelo.addElement(((Graph)this.cb_mod_conexionMapa.getSelectedItem()).getEdge(i).getNode0().toString());
            }
        }
        this.cb_mod_conexionMapa.setModel(modelo);
    }//GEN-LAST:event_cb_mod_palabraMapaActionPerformed

    private void cb_mod_perfilMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mod_perfilMapaActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < ((Perfil)this.cb_mod_perfilMapa.getSelectedItem()).getMapasMentales().size(); i++) {
            modelo.addElement(((Perfil)this.cb_mod_perfilMapa.getSelectedItem()).getMapasMentales().get(i));
        }
        this.cb_mod_mapa.setModel(modelo);
    }//GEN-LAST:event_cb_mod_perfilMapaActionPerformed

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        // TODO add your handling code here:
        this.tf_mod_nombre.setEnabled(false);
        this.ta_mod_obs.setEnabled(false);
        this.cb_mod_raza.setEnabled(false);
        this.rb_mod_femenino.setEnabled(false);
        this.rb_mod_masculino.setEnabled(false);
        this.dc_mod_Fnacimiento.setEnabled(false);
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < perfiles.size(); i++) {
            modelo.addElement(perfiles.get(i));
        }
        this.cb_mod_perfil.setModel(modelo);

    }//GEN-LAST:event_jPanel4ComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < perfiles.size(); i++) {
            if (perfiles.get(i)==perfilModificar) {
                perfiles.remove(i);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < perfiles.size(); i++) {
            if (perfiles.get(i)==perfilModificar) {
                perfiles.get(i).setNombre(this.tf_mod_nombre.getText());
                perfiles.get(i).setObs(this.ta_mod_obs.getText());
                perfiles.get(i).setFechaNacimiento(this.dc_mod_Fnacimiento.getDate());
                perfiles.get(i).setRaza(this.cb_mod_raza.getSelectedItem().toString());
                if (this.rb_mod_femenino.isSelected()) {
                    perfiles.get(i).setGenero("Femenino");
                }else{
                    perfiles.get(i).setGenero("Masculino");
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_mod_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mod_perfilActionPerformed
        // TODO add your handling code here:
        this.perfilModificar=(Perfil)this.cb_mod_perfil.getSelectedItem();
        this.tf_mod_nombre.setEnabled(true);
        this.ta_mod_obs.setEnabled(true);
        this.cb_mod_raza.setEnabled(true);
        this.rb_mod_femenino.setEnabled(true);
        this.rb_mod_masculino.setEnabled(true);
        this.dc_mod_Fnacimiento.setEnabled(true);
        this.tf_mod_nombre.setText(perfilModificar.getNombre());
        this.ta_mod_obs.setText(perfilModificar.getObs());
        this.cb_mod_raza.setSelectedItem(perfilModificar.getRaza());
        if (perfilModificar.getGenero().equals("Femenino")) {
            this.rb_mod_femenino.setSelected(true);
        }else{
            this.rb_mod_masculino.setSelected(true);
        }
        this.dc_mod_Fnacimiento.setDate(perfilModificar.getFechaNacimiento());
    }//GEN-LAST:event_cb_mod_perfilActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        String genero;
        if (this.rb_add_femenino.isSelected()) {
            genero="Femenino";
        }else{
            genero="Masculino";
        }
        Perfil nuevo=new Perfil(this.tf_add_nombre.getText(),this.cb_add_raza.getSelectedItem().toString(),genero,this.dc_add_Fnacimiento.getDate(),
            this.ta_add_obs.getText());
        perfiles.add(nuevo);
        JOptionPane.showMessageDialog(this,"Agregado");
        this.tf_add_nombre.setText("");
        this.ta_add_obs.setText("");
        this.dc_add_Fnacimiento.setDate(null);
        this.cb_add_raza.setSelectedIndex(0);
        this.rb_add_masculino.setSelected(true);
        jd_mapaMental.pack();
        jd_mapaMental.setLocationRelativeTo(this);
        jd_mapaMental.setVisible(true);
        //showDialog(this.jd_mapaMental);
    }//GEN-LAST:event_bt_addActionPerformed

    private void jc_perfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_perfilesActionPerformed
        // TODO add your handling code here:
        jc_mapasMentales.removeAllItems();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        Perfil perfil = (Perfil) jc_perfiles.getSelectedItem();
        for (int i = 0; i < perfil.getMapasMentales().size(); i++) {
            model2.addElement((Graph)perfil.getMapasMentales().get(i));
        }
        jc_mapasMentales.setModel(model2);
    }//GEN-LAST:event_jc_perfilesActionPerformed

    private void jb_mostrarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mostrarMapaActionPerformed
        // TODO add your handling code here:
        Graph mapa = (Graph)jc_mapasMentales.getSelectedItem();
        mapa.display().setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
    }//GEN-LAST:event_jb_mostrarMapaActionPerformed

    private void jb_mostrarPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mostrarPrimActionPerformed
        // TODO add your handling code here:
        Graph mapa = (Graph)jc_mapasMentales.getSelectedItem();
        String css = "edge .notintree {size:1px;fill-color:gray;} " +
        "edge .intree {size:3px;fill-color:black;}";
        mapa.addAttribute("ui.stylesheet", css);
        Prim prim = new Prim("ui.class", "intree", "notintree");
        prim.init(mapa);
        prim.compute();
        mapa.display().setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
    }//GEN-LAST:event_jb_mostrarPrimActionPerformed

    private void jb_actualizarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarTodoActionPerformed
        // TODO add your handling code here:
        jc_perfiles.removeAllItems();
        jc_perfiles.removeAllItems();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Perfil perfil : perfiles) {
            model.addElement((Perfil)perfil);
        }
        jc_perfiles.setModel(model);
    }//GEN-LAST:event_jb_actualizarTodoActionPerformed

    private void jb_agregarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarPalabrasActionPerformed
        // TODO add your handling code here:
        palabras.add(new Palabra(this.tf_add_palabra.getText()));
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < palabras.size(); i++) {
            modelo.addElement((Palabra)palabras.get(i));
        }
        this.cb_add_palabra1.setModel(modelo);
        this.tf_add_palabra.setText("");
    }//GEN-LAST:event_jb_agregarPalabrasActionPerformed

    private void cb_add_palabra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_add_palabra1ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < palabras.size(); i++) {
            if ((Palabra)this.cb_add_palabra1.getSelectedItem()!=(Palabra)palabras.get(i)) {
                modelo.addElement(palabras.get(i));
            }
        }
        this.cb_add_palabra2.setModel(modelo);
    }//GEN-LAST:event_cb_add_palabra1ActionPerformed

    private void jb_crearRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearRelacionActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < palabras.size(); i++) {
            if (palabras.get(i)==this.cb_add_palabra1.getSelectedItem()) {
                ConexionConceptual conexion=new ConexionConceptual(((Palabra)this.cb_add_palabra1.getSelectedItem()).getNombre()+"-"+((Palabra)this.cb_add_palabra2.getSelectedItem()).getNombre()
                    ,Integer.parseInt(this.sp_add_prioridad.getValue()+""),(Palabra)this.cb_add_palabra1.getSelectedItem(),(Palabra)this.cb_add_palabra2.getSelectedItem());
                palabras.get(i).getAdyacencias().add(conexion);
                //System.out.println("Conexion: " +palabras.get(i).getAdyacencias().get(i));
                System.out.println("Agregada A Palabra: " +conexion);
            }
        }
        this.sp_add_prioridad.setValue(1);
        this.cb_add_palabra1.setSelectedIndex(0);
        this.cb_add_palabra2.setSelectedIndex(0);
    }//GEN-LAST:event_jb_crearRelacionActionPerformed

    private void jb_agregarMapaMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarMapaMentalActionPerformed
        // TODO add your handling code here:
        //int a=JOptionPane.showConfirmDialog(this, "Desea finalizar el mapa mental?");
        // if () {
            Graph mapa = new SingleGraph(tf_nombreGrafo.getText());
            for (int i=0; i< palabras.size(); i++) {
                mapa.addNode(palabras.get(i).getNombre()).addAttribute("label", palabras.get(i).getNombre());
            }
            for (Palabra p : palabras) {
                for (int i = 0; i < p.getAdyacencias().size(); i++) {
                    System.out.println("Adyacencia Agregada Al Mapa: " + p.getAdyacencias().get(i));
                    mapa.addEdge(p.getAdyacencias().get(i).getId(),
                        p.getAdyacencias().get(i).getPuntoA().getNombre(),
                        p.getAdyacencias().get(i).getPuntoB().getNombre())
                    .setAttribute("peso", p.getAdyacencias().get(i).getImportancia());
                }
            }
            for (Edge arista : mapa.getEachEdge()) {
                arista.addAttribute("label", (int)arista.getNumber("peso"));
            }
            mapa.display().setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
            perfiles.getLast().getMapasMentales().add(mapa);
            palabras.clear();
            DefaultComboBoxModel modelo=new DefaultComboBoxModel();
            this.cb_add_palabra1.setModel(modelo);
            this.cb_add_palabra2.setModel(modelo);
            tf_nombreGrafo.setText("");
            //}*/
    }//GEN-LAST:event_jb_agregarMapaMentalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    static void showDialog(JDialog d){
        
        d.setLocationRelativeTo(null);
        d.pack();
        d.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_add_palabra1;
    private javax.swing.JComboBox<String> cb_add_palabra2;
    private javax.swing.JComboBox<String> cb_add_raza;
    private javax.swing.JComboBox<String> cb_mod_conexionMapa;
    private javax.swing.JComboBox<String> cb_mod_mapa;
    private javax.swing.JComboBox<String> cb_mod_palabraMapa;
    private javax.swing.JComboBox<String> cb_mod_perfil;
    private javax.swing.JComboBox<String> cb_mod_perfilMapa;
    private javax.swing.JComboBox<String> cb_mod_raza;
    private com.toedter.calendar.JDateChooser dc_add_Fnacimiento;
    private com.toedter.calendar.JDateChooser dc_mod_Fnacimiento;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JButton jb_actualizarTodo;
    private javax.swing.JButton jb_agregarMapaMental;
    private javax.swing.JButton jb_agregarPalabras;
    private javax.swing.JButton jb_crearRelacion;
    private javax.swing.JButton jb_mostrarMapa;
    private javax.swing.JButton jb_mostrarPrim;
    private javax.swing.JComboBox<String> jc_mapasMentales;
    private javax.swing.JComboBox<String> jc_perfiles;
    private javax.swing.JDialog jd_mapaMental;
    private javax.swing.JLabel jl_mapaMental;
    private javax.swing.JLabel jl_perfil;
    private javax.swing.JLabel lb_mod_palabraMapa;
    private javax.swing.JRadioButton rb_add_femenino;
    private javax.swing.JRadioButton rb_add_masculino;
    private javax.swing.JRadioButton rb_mod_femenino;
    private javax.swing.JRadioButton rb_mod_masculino;
    private javax.swing.JSpinner sp_add_prioridad;
    private javax.swing.JSpinner sp_mod_prioridadMapa;
    private javax.swing.JTextArea ta_add_obs;
    private javax.swing.JTextArea ta_mod_obs;
    private javax.swing.JTextField tf_add_nombre;
    private javax.swing.JTextField tf_add_palabra;
    private javax.swing.JTextField tf_mod_nombre;
    private javax.swing.JTextField tf_mod_palabraMapa;
    private javax.swing.JTextField tf_nombreGrafo;
    // End of variables declaration//GEN-END:variables
    LinkedList<Perfil>perfiles=new LinkedList();
    LinkedList<Palabra>palabras=new LinkedList();
    LinkedList<ConexionConceptual>adyacencias=new LinkedList();
    Perfil perfilModificar;

}
